name: Make IPTV EPGPM
on:
  schedule:
    - cron: "0 16 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Download WebGrab+Plus
      run: |
        wget http://webgrabplus.com/sites/default/files/download/SW/V3.2.0/WebGrabPlus_V3.2_install.tar.gz
    - name: Extract WebGrabPlus_V3.2_install.tar.gz
      run: |
        tar -zxvf WebGrabPlus_V3.2_install.tar.gz
    - name: Install WebGrab+Plus
      run: |
        cd .wg++
        ./install.sh
    - name: Download WebGrab++.config.xml
      run: |
        cd .wg++
        wget -N https://raw.githubusercontent.com//StanleyChen0924/IPTV/main/epg.pm.channels.xml
    - name: Run
      run: |
        cd .wg++
        ./run.sh
    - name: Download Other EPG
      run: |
        cd .wg++
        wget https://files.3y1.xyz/static/sitemap/ott_xmltv.xml
    - name: Install xmltv
      run: |
        sudo apt update
        sudo apt -y install xmltv
    - name: Merge EPGPM
      run: |
        cd .wg++
    - name : Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: guide.xml
        path: .wg++/guide.xml
    - name: Git push assets to "EPGPM" branch
      run: |
        cd .wg++
        git init
        git config --local user.name "actions"
        git config --local user.email "action@github.com"
        git checkout -b EPGPM
        git add .
        git commit -m "Update EPGPM"
        git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
        git push -f -u origin EPGPM